import { createServerFn } from "@tanstack/react-start";
type ResultadoFichaFoto={medicacoes:{nome:string;dose:string;duracao:string;via?:string}[];avaliacao:{alimentacao:string;comportamento:string;fezes:string;mucosas:string;temperatura:string;urina:string;fc:string;fr:string;vomito:string;pas:string;glicemia:string};colunaMaisRecente:string;duvidas:string[]};
const INSTRUCAO=`Analise a foto inteira de uma FICHA DE INTERNAÇÃO VETERINÁRIA manuscrita.

A folha normalmente tem DUAS REGIÕES:
- PARTE SUPERIOR: PRESCRIÇÃO/MEDICAÇÕES.
- PARTE INFERIOR: tabela intitulada AVALIAÇÃO. NÃO ignore essa parte inferior.

MEDICAÇÕES: extraia todas as linhas legíveis da prescrição, com nome, dose/volume, intervalo e via.

AVALIAÇÃO: primeiro localize explicitamente a palavra "AVALIAÇÃO" e as linhas à esquerda: ALIMENTAÇÃO, COMPORTAMENTO, FEZES, MUCOSA, TEMPERATURA, URINA, FREQUÊNCIA CARDÍACA, FREQUÊNCIA RESPIRATÓRIA, VÔMITO, PRESSÃO ARTERIAL e GLICEMIA. Depois examine as colunas da direita para a esquerda (MANHÃ/TARDE/NOITE/MADRU ou equivalentes). Escolha a coluna MAIS À DIREITA que contenha pelo menos uma anotação manuscrita: ela representa a avaliação mais recente preenchida. Extraia SOMENTE os valores dessa coluna, respeitando exatamente a linha horizontal correspondente. Um traço ou "N" também conta como anotação e deve ser preservado. Não copie valores de colunas anteriores para completar campos vazios.

Mapeamento obrigatório do JSON: FREQUÊNCIA CARDÍACA -> fc; FREQUÊNCIA RESPIRATÓRIA -> fr; PRESSÃO ARTERIAL -> pas. Se localizar a tabela AVALIAÇÃO mas não conseguir ler um valor, deixe esse campo vazio e descreva em duvidas. Nunca devolva avaliacao inteira vazia sem explicar em duvidas se a tabela estiver visível.

Responda SOMENTE JSON:
{"medicacoes":[{"nome":"","dose":"","duracao":"","via":""}],"avaliacao":{"alimentacao":"","comportamento":"","fezes":"","mucosas":"","temperatura":"","urina":"","fc":"","fr":"","vomito":"","pas":"","glicemia":""},"colunaMaisRecente":"","duvidas":[]}`;
export const lerFichaInternacaoComIA=createServerFn({method:"POST"}).inputValidator((data:{imagem:string})=>{if(typeof data?.imagem!=="string"||!data.imagem.startsWith("data:image/"))throw new Error("Imagem inválida");return data;}).handler(async({data}):Promise<ResultadoFichaFoto>=>{const chave=process.env["LOVABLE_API_KEY"];if(!chave)throw new Error("IA não configurada");const resposta=await fetch("https://ai.gateway.lovable.dev/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${chave}`},body:JSON.stringify({model:"google/gemini-3.7-pro",messages:[{role:"system",content:INSTRUCAO},{role:"user",content:[{type:"text",text:"IMPORTANTE: a avaliação está na metade inferior da mesma foto. Examine a imagem inteira até a borda inferior. Antes de responder, confirme internamente que localizou a linha AVALIAÇÃO e percorreu as colunas da direita para a esquerda. Se a foto estiver inclinada, interprete a tabela mesmo assim."},{type:"image_url",image_url:{url:data.imagem}}]}],response_format:{type:"json_object"}})});if(!resposta.ok)throw new Error(`IA ${resposta.status}`);const json=await resposta.json() as {choices?:{message?:{content?:string}}[]};const texto=json.choices?.[0]?.message?.content??"{}";const i=texto.indexOf("{"),j=texto.lastIndexOf("}");if(i<0||j<=i)throw new Error("Resposta da IA inválida");return JSON.parse(texto.slice(i,j+1)) as ResultadoFichaFoto;});