/** Raças para preencher o receituário. SRD fica sempre no início. */
export const RACAS_CANINAS = [
  "SRD",
  "Affenpinscher",
  "Airedale Terrier",
  "Akita",
  "American Bully",
  "American Staffordshire Terrier",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Bearded Collie",
  "Bedlington Terrier",
  "Bernese Mountain Dog",
  "Bichon Frisé",
  "Bichon Havanês",
  "Bloodhound",
  "Boerboel",
  "Boiadeiro Australiano",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Boxer",
  "Braco Alemão de Pelo Curto",
  "Braco Húngaro",
  "Buldogue Campeiro",
  "Buldogue Francês",
  "Buldogue Inglês",
  "Bull Terrier",
  "Bullmastiff",
  "Cairn Terrier",
  "Cane Corso",
  "Cão da Serra da Estrela",
  "Cão de Água Português",
  "Cão de Crista Chinês",
  "Cão de Montanha dos Pireneus",
  "Cão Lobo Checoslovaco",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Chow Chow",
  "Cocker Spaniel Americano",
  "Cocker Spaniel Inglês",
  "Collie",
  "Coton de Tuléar",
  "Dachshund",
  "Dálmata",
  "Dobermann",
  "Dogo Argentino",
  "Dogue Alemão",
  "Dogue de Bordeaux",
  "Fila Brasileiro",
  "Fox Terrier de Pelo Duro",
  "Fox Terrier de Pelo Liso",
  "Galgo Afegão",
  "Galgo Italiano",
  "Golden Retriever",
  "Griffon de Bruxelas",
  "Husky Siberiano",
  "Jack Russell Terrier",
  "Labrador Retriever",
  "Lagotto Romagnolo",
  "Lhasa Apso",
  "Malamute do Alasca",
  "Maltês",
  "Mastiff",
  "Mastim Napolitano",
  "Mastim Tibetano",
  "Norfolk Terrier",
  "Norwich Terrier",
  "Papillon",
  "Pastor Alemão",
  "Pastor Australiano",
  "Pastor Belga Groenendael",
  "Pastor Belga Malinois",
  "Pastor Belga Tervuren",
  "Pastor Branco Suíço",
  "Pastor de Shetland",
  "Pequinês",
  "Pinscher Miniatura",
  "Pointer Inglês",
  "Poodle",
  "Pug",
  "Rottweiler",
  "Samoieda",
  "São Bernardo",
  "Schipperke",
  "Schnauzer Gigante",
  "Schnauzer Miniatura",
  "Schnauzer Standard",
  "Scottish Terrier",
  "Setter Gordon",
  "Setter Inglês",
  "Setter Irlandês",
  "Shar Pei",
  "Shiba Inu",
  "Shih Tzu",
  "Spaniel Bretão",
  "Spitz Alemão",
  "Staffordshire Bull Terrier",
  "Teckel",
  "Terra-Nova",
  "Terrier Brasileiro",
  "Terrier Galês",
  "Terrier Tibetano",
  "Weimaraner",
  "Welsh Corgi Cardigan",
  "Welsh Corgi Pembroke",
  "West Highland White Terrier",
  "Whippet",
  "Yorkshire Terrier",
] as const;

export const RACAS_FELINAS = [
  "SRD",
  "Abissínio",
  "American Bobtail",
  "American Curl",
  "American Shorthair",
  "Angorá Turco",
  "Balinês",
  "Bengal",
  "Birmanês",
  "Bobtail Japonês",
  "Bombaim",
  "British Longhair",
  "British Shorthair",
  "Burmês",
  "Burmilla",
  "Chartreux",
  "Chantilly-Tiffany",
  "Cornish Rex",
  "Devon Rex",
  "Egyptian Mau",
  "Exótico",
  "Gato da Floresta Norueguês",
  "Gato Siberiano",
  "Havana Brown",
  "Himalaio",
  "Korat",
  "LaPerm",
  "Maine Coon",
  "Manx",
  "Mau Egípcio",
  "Munchkin",
  "Nebelung",
  "Ocicat",
  "Oriental de Pelo Curto",
  "Oriental de Pelo Longo",
  "Persa",
  "Peterbald",
  "Pixie-bob",
  "Ragdoll",
  "Russian Blue",
  "Sagrado da Birmânia",
  "Savannah",
  "Scottish Fold",
  "Selkirk Rex",
  "Siamês",
  "Singapura",
  "Sokoke",
  "Somali",
  "Sphynx",
  "Thai",
  "Tonquinês",
  "Toyger",
] as const;

export type EspecieReceituario = "Canina" | "Felina" | "Outro" | "";

export function racasParaEspecie(especie: EspecieReceituario) {
  if (especie === "Canina") return RACAS_CANINAS;
  if (especie === "Felina") return RACAS_FELINAS;
  return ["SRD", ...RACAS_CANINAS.slice(1), ...RACAS_FELINAS.slice(1)];
}
