import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Save } from "lucide-react";
import { useState } from "react";
import { PLANOS_PADRAO } from "./planos";

export const Route = createFileRoute("/admin-planos")({ component: AdminPlanos });

function AdminPlanos() {
  const [planos, setPlanos] = useState(() => { try { return JSON.parse(localStorage.getItem("vetericio-planos") || "null") || PLANOS_PADRAO; } catch { return [...PLANOS_PADRAO]; } });
  const salvar = () => { localStorage.setItem("vetericio-planos", JSON.stringify(planos)); alert("Planos salvos."); };
  return <main className="min-h-screen bg-background px-4 py-6 sm:px-6"><div className="mx-auto max-w-5xl"><Link to="/" className="inline-flex min-h-10 items-center gap-2 rounded-xl px-3 text-sm font-semibold text-muted-foreground hover:bg-secondary"><ArrowLeft size={18}/> Voltar</Link><h1 className="mt-6 text-3xl font-bold">Administração dos planos</h1><p className="mt-1 text-muted-foreground">Edite as informações que aparecem na página pública de planos.</p><section className="mt-7 space-y-5">{planos.map((plano: any, i: number) => <article key={i} className="rounded-2xl border bg-card p-5"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Nome<input value={plano.nome} onChange={e=>setPlanos((p:any)=>p.map((x:any,j:number)=>j===i?{...x,nome:e.target.value}:x))} className="mt-1 min-h-11 w-full rounded-xl border bg-background px-3 font-normal"/></label><label className="text-sm font-semibold">Preço<input value={plano.preco} onChange={e=>setPlanos((p:any)=>p.map((x:any,j:number)=>j===i?{...x,preco:e.target.value}:x))} className="mt-1 min-h-11 w-full rounded-xl border bg-background px-3 font-normal"/></label></div><label className="mt-3 block text-sm font-semibold">Descrição<textarea value={plano.descricao} onChange={e=>setPlanos((p:any)=>p.map((x:any,j:number)=>j===i?{...x,descricao:e.target.value}:x))} rows={2} className="mt-1 w-full rounded-xl border bg-background px-3 py-2 font-normal"/></label><label className="mt-3 block text-sm font-semibold">Recursos (um por linha)<textarea value={plano.itens.join("\n")} onChange={e=>setPlanos((p:any)=>p.map((x:any,j:number)=>j===i?{...x,itens:e.target.value.split("\n").filter(Boolean)}:x))} rows={5} className="mt-1 w-full rounded-xl border bg-background px-3 py-2 font-normal"/></label></article>)}</section><button onClick={salvar} className="mt-6 inline-flex min-h-12 items-center gap-2 rounded-xl bg-primary px-5 font-semibold text-primary-foreground"><Save size={18}/> Salvar alterações</button></div></main>;
}
