/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvolucaoRouteImport } from './routes/evolucao'
import { Route as PlantoesRouteImport } from './routes/plantoes'
import { Route as RegistrosRouteImport } from './routes/registros'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoRoute = EvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantoesRoute = PlantoesRouteImport.update({
  id: '/plantoes',
  path: '/plantoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrosRoute = RegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evolucao': typeof EvolucaoRoute
  '/plantoes': typeof PlantoesRoute
  '/registros': typeof RegistrosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evolucao': typeof EvolucaoRoute
  '/plantoes': typeof PlantoesRoute
  '/registros': typeof RegistrosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evolucao': typeof EvolucaoRoute
  '/plantoes': typeof PlantoesRoute
  '/registros': typeof RegistrosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/evolucao' | '/plantoes' | '/registros'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/evolucao' | '/plantoes' | '/registros'
  id: '__root__' | '/' | '/evolucao' | '/plantoes' | '/registros'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvolucaoRoute: typeof EvolucaoRoute
  PlantoesRoute: typeof PlantoesRoute
  RegistrosRoute: typeof RegistrosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao': {
      id: '/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof EvolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantoes': {
      id: '/plantoes'
      path: '/plantoes'
      fullPath: '/plantoes'
      preLoaderRoute: typeof PlantoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registros': {
      id: '/registros'
      path: '/registros'
      fullPath: '/registros'
      preLoaderRoute: typeof RegistrosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvolucaoRoute: EvolucaoRoute,
  PlantoesRoute: PlantoesRoute,
  RegistrosRoute: RegistrosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
