/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlarmesRouteImport } from './routes/alarmes'
import { Route as AnamneseRouteImport } from './routes/anamnese'
import { Route as AssinarRouteImport } from './routes/assinar'
import { Route as ConsultorioRouteImport } from './routes/consultorio'
import { Route as CurvaRouteImport } from './routes/curva'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MedicacoesRouteImport } from './routes/medicacoes'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as PlantoesRouteImport } from './routes/plantoes'
import { Route as ReceituarioRouteImport } from './routes/receituario'
import { Route as RecepcaoRouteImport } from './routes/recepcao'
import { Route as RegistrosRouteImport } from './routes/registros'
import { Route as SincronizacaoRouteImport } from './routes/sincronizacao'
import { Route as TemasRouteImport } from './routes/temas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmesRoute = AlarmesRouteImport.update({
  id: '/alarmes',
  path: '/alarmes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnamneseRoute = AnamneseRouteImport.update({
  id: '/anamnese',
  path: '/anamnese',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRoute = AssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorioRoute = ConsultorioRouteImport.update({
  id: '/consultorio',
  path: '/consultorio',
  getParentRoute: () => rootRouteImport,
} as any)
const CurvaRoute = CurvaRouteImport.update({
  id: '/curva',
  path: '/curva',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicacoesRoute = MedicacoesRouteImport.update({
  id: '/medicacoes',
  path: '/medicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantoesRoute = PlantoesRouteImport.update({
  id: '/plantoes',
  path: '/plantoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceituarioRoute = ReceituarioRouteImport.update({
  id: '/receituario',
  path: '/receituario',
  getParentRoute: () => rootRouteImport,
} as any)
const RecepcaoRoute = RecepcaoRouteImport.update({
  id: '/recepcao',
  path: '/recepcao',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrosRoute = RegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => rootRouteImport,
} as any)
const SincronizacaoRoute = SincronizacaoRouteImport.update({
  id: '/sincronizacao',
  path: '/sincronizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const TemasRoute = TemasRouteImport.update({
  id: '/temas',
  path: '/temas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alarmes': typeof AlarmesRoute
  '/anamnese': typeof AnamneseRoute
  '/assinar': typeof AssinarRoute
  '/consultorio': typeof ConsultorioRoute
  '/curva': typeof CurvaRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/medicacoes': typeof MedicacoesRoute
  '/pendencias': typeof PendenciasRoute
  '/plantoes': typeof PlantoesRoute
  '/receituario': typeof ReceituarioRoute
  '/recepcao': typeof RecepcaoRoute
  '/registros': typeof RegistrosRoute
  '/sincronizacao': typeof SincronizacaoRoute
  '/temas': typeof TemasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alarmes': typeof AlarmesRoute
  '/anamnese': typeof AnamneseRoute
  '/assinar': typeof AssinarRoute
  '/consultorio': typeof ConsultorioRoute
  '/curva': typeof CurvaRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/medicacoes': typeof MedicacoesRoute
  '/pendencias': typeof PendenciasRoute
  '/plantoes': typeof PlantoesRoute
  '/receituario': typeof ReceituarioRoute
  '/recepcao': typeof RecepcaoRoute
  '/registros': typeof RegistrosRoute
  '/sincronizacao': typeof SincronizacaoRoute
  '/temas': typeof TemasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alarmes': typeof AlarmesRoute
  '/anamnese': typeof AnamneseRoute
  '/assinar': typeof AssinarRoute
  '/consultorio': typeof ConsultorioRoute
  '/curva': typeof CurvaRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/medicacoes': typeof MedicacoesRoute
  '/pendencias': typeof PendenciasRoute
  '/plantoes': typeof PlantoesRoute
  '/receituario': typeof ReceituarioRoute
  '/recepcao': typeof RecepcaoRoute
  '/registros': typeof RegistrosRoute
  '/sincronizacao': typeof SincronizacaoRoute
  '/temas': typeof TemasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alarmes'
    | '/anamnese'
    | '/assinar'
    | '/consultorio'
    | '/curva'
    | '/estoque'
    | '/financeiro'
    | '/login'
    | '/medicacoes'
    | '/pendencias'
    | '/plantoes'
    | '/receituario'
    | '/recepcao'
    | '/registros'
    | '/sincronizacao'
    | '/temas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alarmes'
    | '/anamnese'
    | '/assinar'
    | '/consultorio'
    | '/curva'
    | '/estoque'
    | '/financeiro'
    | '/login'
    | '/medicacoes'
    | '/pendencias'
    | '/plantoes'
    | '/receituario'
    | '/recepcao'
    | '/registros'
    | '/sincronizacao'
    | '/temas'
  id:
    | '__root__'
    | '/'
    | '/alarmes'
    | '/anamnese'
    | '/assinar'
    | '/consultorio'
    | '/curva'
    | '/estoque'
    | '/financeiro'
    | '/login'
    | '/medicacoes'
    | '/pendencias'
    | '/plantoes'
    | '/receituario'
    | '/recepcao'
    | '/registros'
    | '/sincronizacao'
    | '/temas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlarmesRoute: typeof AlarmesRoute
  AnamneseRoute: typeof AnamneseRoute
  AssinarRoute: typeof AssinarRoute
  ConsultorioRoute: typeof ConsultorioRoute
  CurvaRoute: typeof CurvaRoute
  EstoqueRoute: typeof EstoqueRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LoginRoute: typeof LoginRoute
  MedicacoesRoute: typeof MedicacoesRoute
  PendenciasRoute: typeof PendenciasRoute
  PlantoesRoute: typeof PlantoesRoute
  ReceituarioRoute: typeof ReceituarioRoute
  RecepcaoRoute: typeof RecepcaoRoute
  RegistrosRoute: typeof RegistrosRoute
  SincronizacaoRoute: typeof SincronizacaoRoute
  TemasRoute: typeof TemasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarmes': {
      id: '/alarmes'
      path: '/alarmes'
      fullPath: '/alarmes'
      preLoaderRoute: typeof AlarmesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anamnese': {
      id: '/anamnese'
      path: '/anamnese'
      fullPath: '/anamnese'
      preLoaderRoute: typeof AnamneseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar': {
      id: '/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultorio': {
      id: '/consultorio'
      path: '/consultorio'
      fullPath: '/consultorio'
      preLoaderRoute: typeof ConsultorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curva': {
      id: '/curva'
      path: '/curva'
      fullPath: '/curva'
      preLoaderRoute: typeof CurvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicacoes': {
      id: '/medicacoes'
      path: '/medicacoes'
      fullPath: '/medicacoes'
      preLoaderRoute: typeof MedicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantoes': {
      id: '/plantoes'
      path: '/plantoes'
      fullPath: '/plantoes'
      preLoaderRoute: typeof PlantoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receituario': {
      id: '/receituario'
      path: '/receituario'
      fullPath: '/receituario'
      preLoaderRoute: typeof ReceituarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepcao': {
      id: '/recepcao'
      path: '/recepcao'
      fullPath: '/recepcao'
      preLoaderRoute: typeof RecepcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registros': {
      id: '/registros'
      path: '/registros'
      fullPath: '/registros'
      preLoaderRoute: typeof RegistrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sincronizacao': {
      id: '/sincronizacao'
      path: '/sincronizacao'
      fullPath: '/sincronizacao'
      preLoaderRoute: typeof SincronizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temas': {
      id: '/temas'
      path: '/temas'
      fullPath: '/temas'
      preLoaderRoute: typeof TemasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlarmesRoute: AlarmesRoute,
  AnamneseRoute: AnamneseRoute,
  AssinarRoute: AssinarRoute,
  ConsultorioRoute: ConsultorioRoute,
  CurvaRoute: CurvaRoute,
  EstoqueRoute: EstoqueRoute,
  FinanceiroRoute: FinanceiroRoute,
  LoginRoute: LoginRoute,
  MedicacoesRoute: MedicacoesRoute,
  PendenciasRoute: PendenciasRoute,
  PlantoesRoute: PlantoesRoute,
  ReceituarioRoute: ReceituarioRoute,
  RecepcaoRoute: RecepcaoRoute,
  RegistrosRoute: RegistrosRoute,
  SincronizacaoRoute: SincronizacaoRoute,
  TemasRoute: TemasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
